name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: dotnet tests
    runs-on: ubuntu-latest
    strategy:
     matrix:
        include:
        - dotnet-version: '3.1.x'
          tfm: 'netcoreapp3.1'

    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '3.1.301'
          include-prerelease: true

    - name: Build with dotnet
      run: dotnet build
    
    - name: Test
      #run: dotnet test --no-build --verbosity normal -f=${{ matrix.tfm }}
      run: dotnet test --no-build --verbosity normal
